// Code generated by MockGen. DO NOT EDIT.
// Source: main.go
//
// Generated by this command:
//
//	mockgen -source=main.go -destination=item_repository_mock_test.go -package=main
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	database "my-api/internal/database"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockItemRepository is a mock of ItemRepository interface.
type MockItemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockItemRepositoryMockRecorder
	isgomock struct{}
}

// MockItemRepositoryMockRecorder is the mock recorder for MockItemRepository.
type MockItemRepositoryMockRecorder struct {
	mock *MockItemRepository
}

// NewMockItemRepository creates a new mock instance.
func NewMockItemRepository(ctrl *gomock.Controller) *MockItemRepository {
	mock := &MockItemRepository{ctrl: ctrl}
	mock.recorder = &MockItemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockItemRepository) EXPECT() *MockItemRepositoryMockRecorder {
	return m.recorder
}

// GetItem mocks base method.
func (m *MockItemRepository) GetItem(ctx context.Context, id int) (database.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", ctx, id)
	ret0, _ := ret[0].(database.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockItemRepositoryMockRecorder) GetItem(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockItemRepository)(nil).GetItem), ctx, id)
}

// MockitemGetter is a mock of itemGetter interface.
type MockitemGetter struct {
	ctrl     *gomock.Controller
	recorder *MockitemGetterMockRecorder
	isgomock struct{}
}

// MockitemGetterMockRecorder is the mock recorder for MockitemGetter.
type MockitemGetterMockRecorder struct {
	mock *MockitemGetter
}

// NewMockitemGetter creates a new mock instance.
func NewMockitemGetter(ctrl *gomock.Controller) *MockitemGetter {
	mock := &MockitemGetter{ctrl: ctrl}
	mock.recorder = &MockitemGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockitemGetter) EXPECT() *MockitemGetterMockRecorder {
	return m.recorder
}

// GetItem mocks base method.
func (m *MockitemGetter) GetItem(arg0 context.Context, arg1 int) (database.Item, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetItem", arg0, arg1)
	ret0, _ := ret[0].(database.Item)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetItem indicates an expected call of GetItem.
func (mr *MockitemGetterMockRecorder) GetItem(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetItem", reflect.TypeOf((*MockitemGetter)(nil).GetItem), arg0, arg1)
}
